- name: Install deps
  ansible.builtin.apt:
    lock_timeout: 120
    update_cache: true
    pkg:
      - iptables-persistent
      - frr
      - cron

- name: Netplan dummy0 interface
  ansible.builtin.template:
    src: netplan_dummy0.yaml.j2
    dest: /etc/netplan/dummy0.yaml
    mode: "640"

- name: Netplan dummy1 interface
  ansible.builtin.template:
    src: netplan_dummy1.yaml.j2
    dest: /etc/netplan/dummy1.yaml
    mode: "640"
  when: EXTERNAL_LISTEN_IP != ""

- name: Netplan dummy2 interface
  ansible.builtin.template:
    src: netplan_dummy2.yaml.j2
    dest: /etc/netplan/dummy2.yaml
    mode: "640"

- name: Netplan dummy3 interface
  ansible.builtin.template:
    src: netplan_dummy3.yaml.j2
    dest: /etc/netplan/dummy3.yaml
    mode: "640"
  when: EXTERNAL_OUTGOING_IP != ""

- name: Netplan eth0 interface
  ansible.builtin.template:
    src: netplan_50_cloud_init.yaml.j2
    dest: /etc/netplan/50-cloud-init.yaml
    mode: "640"

- name: Enable ospfd
  ansible.builtin.lineinfile:
    path: /etc/frr/daemons
    search_string: ospfd=no
    line: "ospfd=yes"

- name: Config template frr
  ansible.builtin.template:
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
    mode: "640"

- name: Iptables rules
  ansible.builtin.template:
    src: iptables.j2
    dest: /etc/iptables/rules.v4
    mode: "600"

- name: Restore iptables rules
  ansible.builtin.command:
    cmd: "bash -c '/sbin/iptables-restore < /etc/iptables/rules.v4'"

- name: Netplan apply
  ansible.builtin.command:
    cmd: "bash -c 'netplan apply && touch /tmp/netplan_applied'"
    creates: /tmp/netplan_applied

- name: Restart and enable iptables service
  ansible.builtin.service:
    name: netfilter-persistent
    state: restarted
    enabled: true

- name: Set net.ipv4.ip_forward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Allow restarting of frr
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/frr.service
    search_string: Restart=
    line: "Restart=always"

- name: Restart and enable frr service
  ansible.builtin.systemd_service:
    name: frr
    state: restarted
    enabled: true
    daemon_reload: true

- name: Crontab
  ansible.builtin.lineinfile:
    path: /etc/cron.d/frr_reload
    line: "28 */3 * * *   root    systemctl restart frr.service"
    create: true
    mode: "600"

- name: Restart and enable cron service
  ansible.builtin.systemd_service:
    state: restarted
    name: cron
    enabled: true

- name: Set net.ipv4.ip_forward again
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
