- name: Install deps
  ansible.builtin.apt:
    lock_timeout: 120
    update_cache: true
    pkg:
      - python3-passlib

- name: Add the user 'support'
  ansible.builtin.user:
    name: support
    uid: 1001
    password: "{{ LOCAL_PASSWORD | password_hash('sha512') }}"
    groups: sudo
