- name: Knot authoritative
  hosts: knot-authoritative
  become: true
  roles:
    - role: dns-ssh
    - role: dns-frr
    - role: dns-telegraf
    - role: knot-authoritative
    - role: support-account

- name: Knot recursive
  hosts: knot-recursive
  become: true
  roles:
    - role: dns-ssh
    - role: knot-recursive
    - role: dns-frr
    - role: dns-telegraf
    - role: support-account
