- name: Knot authoritative
  hosts: knot-authoritative
  become: true
  roles:
    - role: dns_ssh
    - role: dns_ospf
    - role: dns_telegraf
    - role: knot_authoritative
    - role: support_account

- name: Knot recursive
  hosts: knot-recursive
  become: true
  roles:
    - role: dns_ssh
    - role: dns_ospf
    - role: dns_telegraf
    - role: knot_recursive
    - role: support_account
