name: Deploy

on:
  push:
    branches:
      - master
      - james/tsig_keys
    paths:
      - infra/**
  workflow_dispatch:

permissions: read-all

jobs:
  deploy_jon:
    name: Deploy to jon
    uses: ./.github/workflows/deploy_dns_environment.yaml
    with:
      environment: dev_jon
    secrets: inherit
    # if: github.ref == 'refs/heads/master'

  deploy_sn10_prod:
    name: Deploy to sn10 prod
    uses: ./.github/workflows/deploy_dns_environment.yaml
    needs: deploy_jon
    with:
      environment: prod_sn10
    secrets: inherit
    if: github.ref == 'refs/heads/master'

  deploy_sn3_prod:
    name: Deploy to sn3 prod
    uses: ./.github/workflows/deploy_dns_environment.yaml
    needs: deploy_sn10_prod
    with:
      environment: prod_sn3
    secrets: inherit
    if: github.ref == 'refs/heads/master'
