name: Deploy

on:
  push:
    branches:
      - master
      - james/infra4 # JBOTODO: cleanup
    paths:
      - infra/**
  workflow_dispatch:
    branches:
      - master

permissions: read-all

jobs:
  deploy_jon:
    name: Deploy to jon
    uses: ./.github/workflows/deploy_dns_environment.yaml
    with:
      environment: dev_jon
    secrets: inherit
    if: github.ref == 'refs/heads/james/infra4' && github.event_name == 'push'
    #if: github.ref == 'refs/heads/master' && github.event_name == 'push'

  deploy_sn3_prod:
    name: Deploy to sn3 prod
    uses: ./.github/workflows/deploy_dns_environment.yaml
    needs: deploy_jon
    with:
      environment: sn3_prod
    secrets: inherit
    if: github.ref == 'refs/heads/james/infra4' && github.event_name == 'push'
    # if: github.ref == 'refs/heads/master' && github.event_name == 'push'
